#include<stdio.h>
#include<conio.h>
main()
{
      clrscr();
     printf("\t\t\t-\t-\t-\t-\t\n");
     printf("\t\t|\t\t\t\t\t|\n\n");
     printf("\t\t|\t\t\t\t\t|\n\n");
     printf("\t\t|\t\t\t\t\t|\n\n");
     printf("\t\tJ\t\t\t\t\t|\n\n");
     printf("\t\tE\t\t\t\t\t|\n\n");
     printf("\t\tN\t\t\t\t\t|\n\n");
     printf("\t\tI\t\t\t\t\t|\n\n");
     printf("\t\tS\t\t\t\t\t|\n\n");
     printf("\t\tH\t\t\t\t\t|\n\n");
     printf("\t\t|\t\t\t\t\t|\n\n");
     printf("\t\t|\t\t\t\t\t|\n\n");
     printf("\t\t|\t\t\t\t\t|\n");
     printf("\t\t\t-\t-\t-\t-\t");
     getch();
}